# Generated by Django 6.0.6 on 2026-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepolicy",
            name="writable_types",
            field=models.JSONField(default=list),
        ),
    ]
